In [1]:
import numpy as np

In [3]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
s = slice(2,18,3)

In [6]:
a[s]

array([ 2,  5,  8, 11, 14, 17])

In [10]:
b=a[2:18:3]
print(b)

[ 2  5  8 11 14 17]


In [12]:
c=a[5:]
c

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
d=a[5:10]
d

array([5, 6, 7, 8, 9])

In [32]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [33]:
arr2=arr[2:5:2]
arr2

array([[ 7,  8,  9],
       [13, 14, 15]])

In [34]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [35]:
#Ellipsis
print('Slicing a column, row using ELLIPSIS ')

Slicing a column, row using ELLIPSIS 


In [36]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [39]:
arr[...,1]

array([ 2,  5,  8, 11, 14, 17, 20])

In [41]:
a1=arr[...,1:3]

In [42]:
a1

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12],
       [14, 15],
       [17, 18],
       [20, 21]])

In [43]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [44]:
arr[1:4,...]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])