# Advancd Indexing using Numpy

In [30]:
import numpy as np

In [31]:
print("Two types: INTEGER AND BOOLEAN")

Two types: INTEGER AND BOOLEAN


In [32]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [33]:
arr[[0],[1]]

array([2])

In [34]:
arr 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [35]:
arr[[2,3,5],[0,1,2]]

array([ 7, 11, 18])

In [36]:
rows = np.array([[0,0],[6,6]])
cols = np.array([[0,2],[0,2]])

arr[rows, cols]

array([[ 1,  3],
       [19, 21]])

In [37]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [38]:
arr[1:4, 1:3]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [39]:
arr[1:4, [1,2]]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [40]:
print('BOOLEAN ADVANCE INDEXING')

BOOLEAN ADVANCE INDEXING


In [41]:
arr[arr>11]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [42]:
arr2 =np.array([[1,2,np.nan],[np.nan,5,6],[7,np.nan,9],[10,11,np.nan],[np.nan,14,15],[16,np.nan,18],[np.nan,20,21]])
arr2

array([[ 1.,  2., nan],
       [nan,  5.,  6.],
       [ 7., nan,  9.],
       [10., 11., nan],
       [nan, 14., 15.],
       [16., nan, 18.],
       [nan, 20., 21.]])

In [43]:
a=arr2[~np.isnan(arr2)]
a

array([ 1.,  2.,  5.,  6.,  7.,  9., 10., 11., 14., 15., 16., 18., 20.,
       21.])