In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr + arr2

array([ 6,  8, 10, 12])

In [3]:
arr * arr2

array([ 5, 12, 21, 32])

In [4]:
arr / arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [5]:
arr % arr2

array([1, 2, 3, 4])

In [9]:
ar = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ar2 = np.array([13,14,15,16])

In [10]:
ar + ar2

array([[14, 16, 18, 20],
       [18, 20, 22, 24],
       [22, 24, 26, 28]])