# N-Dimensional Iterator

In [1]:
import numpy as np

In [2]:
r = np.arange(0,60,5)
r

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [3]:
s = r.reshape(3,4)

In [4]:
s

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [5]:
for i in np.nditer(s):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


### Tranpose Shape of array

In [6]:
t = s.T
t

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [7]:
for i in np.nditer(t):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


#### Iteration Order [ F-Style or C-Style]

In [8]:
s

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [9]:
c = s.copy(order = 'C')
for i in np.nditer(c):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


In [10]:
f = s.copy(order = 'F')
for i in np.nditer(f):
    print(i)

0
20
40
5
25
45
10
30
50
15
35
55


#### Second Method for F-Stype or C-Stype iteration

In [11]:
for i in np.nditer(s, order = 'F'):
    print(i)

0
20
40
5
25
45
10
30
50
15
35
55


In [12]:
for i in np.nditer(s, order = 'C'):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


#### Modifying Array values using NdIter and flags called 'op_flags'

In [13]:
s

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [16]:
sec = np.array([1,2,3,4], dtype=int)
sec

array([1, 2, 3, 4])

In [25]:
for i,j in np.nditer([s,sec]):
    print (i*j)

0
10
30
60
20
50
90
140
40
90
150
220


In [24]:
sec

array([1, 2, 3, 4])

In [26]:
s

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])