# Array Manipulation 

In [1]:
import numpy as np

## Change Shape

###### There are number of routines are available in Numpy
1. reshape
2. flat
3. flatten
4. reval

#### Reshape

In [2]:
arr = np.arange(0,60,5)
shape =arr
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [3]:
arr=arr.reshape(4,3)

In [4]:
arr

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [5]:
arr=arr.reshape(3,4)
arr

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

#### Flat- It take the index and return the value of that index in 1-D array

In [6]:
a = np.arange(8).reshape(2,4) 
print (a.flat[5])

5


In [7]:
shape.reshape(2,6)

array([[ 0,  5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50, 55]])

In [8]:
shape.flat[10]

50

In [9]:
arr.flat[4]

20

#### Flatten - It returns the N-Dimensional array into 1-D

In [10]:
arr

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [11]:
arr.reshape(4,3)

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [12]:
arr.flatten()

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [13]:
arr

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [14]:
arr.reshape(4,3)

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [15]:
arr.flatten(order='F')

array([ 0, 20, 40,  5, 25, 45, 10, 30, 50, 15, 35, 55])

#### Ravel - It returns the same array as of Input array

In [16]:
arr.reshape(3,4)

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [17]:
arr.ravel(order = 'C')

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

### Transpose operation

#### Tyes of Transpose operations
1. transpose
2. ndarray.T same as transpose
3. rollaxis
4. swapaxes

In [18]:
arr

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

##### Transpose

In [19]:
arr=np.transpose(arr)

In [20]:
arr 

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

##### Rollaxis

In [21]:
arr

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [22]:
arr=arr.reshape(6,2)

In [23]:
arr

array([[ 0, 20],
       [40,  5],
       [25, 45],
       [10, 30],
       [50, 15],
       [35, 55]])

In [24]:
arr=np.array(arr).reshape(2,2,3)

In [25]:
arr

array([[[ 0, 20, 40],
        [ 5, 25, 45]],

       [[10, 30, 50],
        [15, 35, 55]]])

In [26]:
np.rollaxis(arr,2)

array([[[ 0,  5],
        [10, 15]],

       [[20, 25],
        [30, 35]],

       [[40, 45],
        [50, 55]]])

In [27]:
ar = np.ones((1,2,3,4))
ar

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [28]:
np.rollaxis(ar,3,1).shape

(1, 4, 2, 3)

## Needs to find out how rollaxiz and swapaxes works

##### ============================================================

#### SwapAxes

In [29]:
arr

array([[[ 0, 20, 40],
        [ 5, 25, 45]],

       [[10, 30, 50],
        [15, 35, 55]]])

In [30]:
arr=arr.reshape(4,3)
arr

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [31]:
np.swapaxes(arr,1,0)

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [32]:
arr

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

## Joining Arrays

#### Methods
1. Concatenate
2. stack
3. hstack
4. vstack

#### CONCATENATE

In [33]:
a=np.array([[1,2],[3,4]],dtype=int)
a

array([[1, 2],
       [3, 4]])

In [34]:
b=np.array([[5,6],[7,8]], dtype=int)
b

array([[5, 6],
       [7, 8]])

In [35]:
o=np.concatenate([a,b])
o

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
a, b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [37]:
np.concatenate([b,a],1)

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

#### STACK

In [38]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [39]:
np.stack([a,b])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
np.stack([a,b],1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [41]:
np.stack([a,b],2)

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

#### HSTACK

In [42]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [43]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### VSTACK

In [45]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [46]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Changing Dimensions

#### Methods
1. Broadcast
2. Broadcast_to
3. Expand_dims
4. Squeeze

In [48]:
c = np.array([[1],[2],[3]])
d = np.array([4,5,6])
c,d

(array([[1],
        [2],
        [3]]),
 array([4, 5, 6]))

In [64]:
b = np.broadcast(c,d)
b

In [52]:
b.shape

(3, 3)

In [65]:
e,f = b.iters

In [66]:
print(e.next()) # f.next()

AttributeError: 'numpy.flatiter' object has no attribute 'next'